=== 3166790565/Euro-Truck-Simulator-2-Lane-Assist/ETS2LA/plugins/schema.json
{
    "$schema": "http://json-schema.org/schema",
    "properties": {
        "name": {
            "type": "string",
            "description": "The name of the plugin."
        },
        "authors": {
            "type": "array",
            "description": "The authors of the plugin.",
            "items": {
                "name": "string",
                "url": "string",
                "avatar": "string"
            }
        },
        "description": {
            "type": "string",
            "description": "The description of the plugin."
        },
        "version": {
            "type": "string",
            "description": "The version of the plugin."
        },
        "dependencies": {
            "type": "array",
            "description": "The dependencies of the plugin.",
            "items": {
                "name": "string"
            }
        },
        "modules": {
            "type": "array",
            "description": "List of modules the plugin runner will load.",
            "items": {
                "name": ["ScreenCapture", "SDKController", "ShowImage", "TruckSimAPI"]
            }
        },
        "compatible": {
            "type": "array",
            "description": "List of compatible operating systems.",
            "items": {
                "name": ["Windows", "Linux", "MacOS"]
            }
        }
    }
}

=== 3166790565/Euro-Truck-Simulator-2-Lane-Assist/ETS2LA/plugins/DepthPrediction/plugin.json
{
    "name": "Depth Prediction",
    "authors": [{
        "name": "Tumppi066",
        "url": "https://github.com/Tumppi066",
        "avatar": "https://avatars.githubusercontent.com/u/83072683?v=4"
    }],
    "description": "Provides depth prediction for object avoidance, please note that this plugin may only work on NVIDIA graphics cards, due to the sheer performance requirements.",
    "version": "1.0",
    "modules": ["ScreenCapture", "ShowImage"]
}

=== 3166790565/Euro-Truck-Simulator-2-Lane-Assist/ETS2LA/plugins/DiscordRichPresence/plugin.json
{
    "name": "plugins.discordrichpresence",
    "authors": [{
        "name": "DylDev",
        "url": "https://github.com/DylDevs",
        "avatar": "https://avatars.githubusercontent.com/u/110776467?v=4"
    }],
    "description": "plugins.discordrichpresence.description",
    "version": "1.0",
    "dependencies": [],
    "modules": ["TruckSimAPI"],
    "compatible": ["Windows", "Linux", "MacOS"]
}

=== 3166790565/Euro-Truck-Simulator-2-Lane-Assist/ETS2LA/old_plugins/CruiseControl/plugin.json
{
    "name": "plugins.cruisecontrol",
    "authors": [{
        "name": "Glas42",
        "url": "https://github.com/Glas42",
        "avatar": "https://avatars.githubusercontent.com/u/145870870?v=4"
    }],
    "description": "plugins.cruisecontrol.description",
    "version": "1.0",
    "dependencies": [],
    "modules": ["TruckSimAPI", "SDKController"]
}
