=== 3166790565/Euro-Truck-Simulator-2-Lane-Assist/ETS2LA/plugins/schema.json
{
    "$schema": "http://json-schema.org/schema",
    "properties": {
        "name": {
            "type": "string",
            "description": "The name of the plugin."
        },
        "authors": {
            "type": "array",
            "description": "The authors of the plugin.",
            "items": {
                "name": "string",
                "url": "string",
                "avatar": "string"
            }
        },
        "description": {
            "type": "string",
            "description": "The description of the plugin."
        },
        "version": {
            "type": "string",
            "description": "The version of the plugin."
        },
        "dependencies": {
            "type": "array",
            "description": "The dependencies of the plugin.",
            "items": {
                "name": "string"
            }
        },
        "modules": {
            "type": "array",
            "description": "List of modules the plugin runner will load.",
            "items": {
                "name": ["ScreenCapture", "SDKController", "ShowImage", "TruckSimAPI"]
            }
        },
        "compatible": {
            "type": "array",
            "description": "List of compatible operating systems.",
            "items": {
                "name": ["Windows", "Linux", "MacOS"]
            }
        }
    }
}

=== 3166790565/Euro-Truck-Simulator-2-Lane-Assist/ETS2LA/plugins/Map/plugin.json
{
    "name": "Map",
    "authors": [{
        "name": "Tumppi066",
        "url": "https://github.com/Tumppi066",
        "avatar": "https://avatars.githubusercontent.com/u/83072683?v=4"
    }],
    "description": "Map detection plugin.",
    "version": "1.0",
    "modules": ["TruckSimAPI", "ShowImage"]
}

=== 3166790565/Euro-Truck-Simulator-2-Lane-Assist/ETS2LA/old_plugins/DepthPrediction/plugin.json
{
    "name": "plugins.depthprediction",
    "authors": [{
        "name": "Tumppi066",
        "url": "https://github.com/Tumppi066",
        "avatar": "https://avatars.githubusercontent.com/u/83072683?v=4"
    }],
    "description": "plugins.depthprediction.description",
    "version": "1.0",
    "modules": ["ScreenCapture", "ShowImage"]
}

=== 3166790565/Euro-Truck-Simulator-2-Lane-Assist/ETS2LA/plugins/DataCollection/plugin.json
{
    "name": "plugins.datacollection",
    "authors": [{
        "name": "DylDev",
        "url": "https://github.com/DylDevs",
        "avatar": "https://avatars.githubusercontent.com/u/110776467?v=4"
    }],
    "description": "plugins.datacollection.description",
    "version": "1.0",
    "dependencies": [],
    "modules": ["ScreenCapture"],
    "compatible": ["Windows", "Linux", "MacOS"]
}

=== 3166790565/Euro-Truck-Simulator-2-Lane-Assist/ETS2LA/old_plugins/Sockets/plugin.json
{
    "name": "plugins.sockets",
    "authors": [{
        "name": "Tumppi066",
        "url": "https://github.com/Tumppi066",
        "avatar": "https://avatars.githubusercontent.com/u/83072683?v=4"
    }],
    "description": "plugins.sockets.description",
    "version": "1.0",
    "modules": ["TruckSimAPI"]
}

=== 3166790565/Euro-Truck-Simulator-2-Lane-Assist/ETS2LA/plugins/Test/plugin.json
{
    "name": "Test",
    "authors": [{
        "name": "Tumppi066",
        "url": "https://github.com/Tumppi066",
        "avatar": "https://avatars.githubusercontent.com/u/83072683?v=4"
    }],
    "description": "Test",
    "version": "1.0",
    "dependencies": [],
    "modules": ["ScreenCapture"],
    "compatible": ["Windows", "Linux", "MacOS"]
}

=== 3166790565/Euro-Truck-Simulator-2-Lane-Assist/ETS2LA/plugins/VehicleDetection/plugin.json
{
    "name": "VehicleDetection",
    "authors": [{
        "name": "DylDev",
        "url": "https://github.com/DylDevs",
        "avatar": "https://avatars.githubusercontent.com/u/110776467?v=4"
    }],
    "description": "Detects vehicles using computer vision and can display them in an output window.",
    "version": "1.0",
    "dependencies": [],
    "modules": ["ScreenCapture", "ShowImage", "Raycasting", "TruckSimAPI"],
    "compatible": ["Windows", "Linux", "MacOS"]
}

=== 3166790565/Euro-Truck-Simulator-2-Lane-Assist/ETS2LA/old_plugins/TruckStats/plugin.json
{
    "name": "plugins.truckstats",
    "authors": [{
        "name": "Glas42",
        "url": "https://github.com/Glas42",
        "avatar": "https://avatars.githubusercontent.com/u/145870870?v=4"
    }],
    "description": "plugins.truckstats.description",
    "version": "1.0",
    "dependencies": [],
    "modules": ["TruckSimAPI"]
}

=== 3166790565/Euro-Truck-Simulator-2-Lane-Assist/ETS2LA/old_plugins/MicrocontrollerControl/plugin.json
{
    "name": "plugins.microcontrollercontrol",
    "authors": [{
        "name": "DylDev",
        "url": "https://github.com/DylDevs",
        "avatar": "https://avatars.githubusercontent.com/u/110776467?v=4"
    }],
    "description": "plugins.microcontrollercontrol.description",
    "version": "1.0",
    "dependencies": [],
    "modules": ["TruckSimAPI"],
    "compatible": ["Windows", "Linux", "MacOS"]
}
