=== 3166790565/Euro-Truck-Simulator-2-Lane-Assist/ETS2LA/plugins/schema.json
{
    "$schema": "http://json-schema.org/schema",
    "properties": {
        "name": {
            "type": "string",
            "description": "The name of the plugin."
        },
        "authors": {
            "type": "array",
            "description": "The authors of the plugin.",
            "items": {
                "name": "string",
                "url": "string",
                "avatar": "string"
            }
        },
        "description": {
            "type": "string",
            "description": "The description of the plugin."
        },
        "version": {
            "type": "string",
            "description": "The version of the plugin."
        },
        "dependencies": {
            "type": "array",
            "description": "The dependencies of the plugin.",
            "items": {
                "name": "string"
            }
        },
        "modules": {
            "type": "array",
            "description": "List of modules the plugin runner will load.",
            "items": {
                "name": ["ScreenCapture", "SDKController", "ShowImage", "TruckSimAPI"]
            }
        },
        "compatible": {
            "type": "array",
            "description": "List of compatible operating systems.",
            "items": {
                "name": ["Windows", "Linux", "MacOS"]
            }
        }
    }
}

=== 3166790565/Euro-Truck-Simulator-2-Lane-Assist/ETS2LA/plugins/Sockets/plugin.json
{
    "name": "Sockets",
    "authors": [{
        "name": "Tumppi066",
        "url": "https://github.com/Tumppi066",
        "avatar": "https://avatars.githubusercontent.com/u/83072683?v=4"
    }],
    "description": "Plugin to make a data socket available mainly for the built in visualisation.",
    "version": "1.0",
    "modules": ["TruckSimAPI"]
}

=== 3166790565/Euro-Truck-Simulator-2-Lane-Assist/ETS2LA/plugins/TrafficLightDetection/plugin.json
{
    "name": "plugins.trafficlightdetection",
    "authors": [{
        "name": "Glas42",
        "url": "https://github.com/Glas42",
        "avatar": "https://avatars.githubusercontent.com/u/145870870?v=4"
    }],
    "description": "plugins.trafficlightdetection.description",
    "version": "0.7",
    "dependencies": [],
    "modules": ["TruckSimAPI", "ScreenCapture"]
}

=== 3166790565/Euro-Truck-Simulator-2-Lane-Assist/ETS2LA/plugins/MicrocontrollerControl/plugin.json
{
    "name": "MicrocontrollerControl",
    "authors": [{
        "name": "DylDev",
        "url": "https://github.com/DylDevs",
        "avatar": "https://avatars.githubusercontent.com/u/110776467?v=4"
    }],
    "description": "Allows you to control ETS2LA and ETS2 from a microcontroller (Made for button boxes)",
    "version": "1.0",
    "dependencies": [],
    "modules": ["TruckSimAPI"],
    "compatible": ["Windows", "Linux", "MacOS"]
}

=== 3166790565/Euro-Truck-Simulator-2-Lane-Assist/ETS2LA/plugins/NavigationDetection/plugin.json
{
    "name": "NavigationDetection",
    "authors": [{
        "name": "Glas42",
        "url": "https://github.com/Glas42",
        "avatar": "https://avatars.githubusercontent.com/u/145870870?v=4"
    }],
    "description": "Uses the in-game route advisor to follow the selected route.",
    "version": "3.1",
    "dependencies": [],
    "modules": ["TruckSimAPI", "Steering", "ShowImage", "ScreenCapture", "SDKController"]
}

=== 3166790565/Euro-Truck-Simulator-2-Lane-Assist/ETS2LA/plugins/CruiseControl/plugin.json
{
    "name": "CruiseControl",
    "authors": [{
        "name": "Glas42",
        "url": "https://github.com/Glas42",
        "avatar": "https://avatars.githubusercontent.com/u/145870870?v=4"
    }],
    "description": "Sets the in-game cruise control to the correct speed.",
    "version": "1.0",
    "dependencies": [],
    "modules": ["TruckSimAPI", "SDKController"]
}

=== 3166790565/Euro-Truck-Simulator-2-Lane-Assist/ETS2LA/plugins/TruckStats/plugin.json
{
    "name": "TruckStats",
    "authors": [{
        "name": "Glas42",
        "url": "https://github.com/Glas42",
        "avatar": "https://avatars.githubusercontent.com/u/145870870?v=4"
    }],
    "description": "This plugin shows some statistics about the truck, route and the game.",
    "version": "1.0",
    "dependencies": [],
    "modules": ["TruckSimAPI"]
}

=== 3166790565/Euro-Truck-Simulator-2-Lane-Assist/ETS2LA/plugins/AdaptiveCruiseControlTest/plugin.json
{
    "name": "AdaptiveCruiseControlTest",
    "authors": [{
        "name": "DylDev",
        "url": "https://github.com/DylDevs",
        "avatar": "https://avatars.githubusercontent.com/u/110776467?v=4"
    }],
    "description": "WIP - Cruise Control using vehicle position data and speed limit.",
    "version": "1.0",
    "dependencies": [],
    "modules": ["ShowImage", "TruckSimAPI", "SDKController", "MapUtils"],
    "compatible": ["Windows", "Linux", "MacOS"]
}

=== 3166790565/Euro-Truck-Simulator-2-Lane-Assist/ETS2LA/old_plugins/RaycastingTest/plugin.json
{
    "name": "plugins.raycastingtest",
    "authors": [{
        "name": "Tumppi066",
        "url": "https://github.com/Tumppi066",
        "avatar": "https://avatars.githubusercontent.com/u/83072683?v=4"
    }],
    "description": "plugins.raycastingtest.description",
    "version": "1.0",
    "modules": ["Raycasting", "TruckSimAPI"]
}
