=== 3166790565/Euro-Truck-Simulator-2-Lane-Assist/ETS2LA/old_plugins/schema.json
{
    "$schema": "http://json-schema.org/schema",
    "properties": {
        "name": {
            "type": "string",
            "description": "The name of the plugin."
        },
        "authors": {
            "type": "array",
            "description": "The authors of the plugin.",
            "items": {
                "name": "string",
                "url": "string",
                "avatar": "string"
            }
        },
        "description": {
            "type": "string",
            "description": "The description of the plugin."
        },
        "version": {
            "type": "string",
            "description": "The version of the plugin."
        },
        "dependencies": {
            "type": "array",
            "description": "The dependencies of the plugin.",
            "items": {
                "name": "string"
            }
        },
        "modules": {
            "type": "array",
            "description": "List of modules the plugin runner will load.",
            "items": {
                "name": ["ScreenCapture", "SDKController", "ShowImage", "TruckSimAPI"]
            }
        },
        "compatible": {
            "type": "array",
            "description": "List of compatible operating systems.",
            "items": {
                "name": ["Windows", "Linux", "MacOS"]
            }
        },
        "settings": {
            "type": "array",
            "description": "Settings data to display on the frontend",
            "items": {
                "type": "object",
                "description": "A setting in the settings file.",
                "properties": {
                    "specials": {
                        "type": "array",
                        "description": "Special stuff that's not actually settings.",
                        "items": {
                            "type": "object",
                            "properties": {
                                "special": {
                                    "type": "string",
                                    "description": "The special type.",
                                    "enum": ["Title", "Description", "Separator", "Space"]
                                },
                                "special_data": {
                                    "type": ["integer", "string"],
                                    "description": "The special data."
                                }
                            }
                        }
                    },
                    "name": {
                        "type": "string",
                        "description": "The name of the setting."
                    },
                    "key": {
                        "type": "string",
                        "description": "The setting key in the settings file."
                    },
                    "description": {
                        "type": "string",
                        "description": "The description of the setting."
                    },
                    "requires_restart": {
                        "type": "boolean",
                        "description": "Whether the setting requires a restart to take effect."
                    },
                    "type": {
                        "type": "object",
                        "description": "The type of the setting.",
                        "properties": {
                            "type": {
                                "type": "string",
                                "description": "The name of the setting type.",
                                "enum": ["string", "number", "boolean", "array", "object", "enum"]
                            },
                            "options": {
                                "type": "array",
                                "description": "If applicable (enum), the options for the setting.",
                                "items": {
                                    "data": "string"
                                }
                            },
                            "value_type":
                            {
                                "type": "string",
                                "description": "If applicable (array), the type of the values in the array.",
                                "enum": ["text", "number", "email", "url"]
                            },
                            "default":
                            {
                                "type": ["string", "number", "boolean", "array", "object"],
                                "description": "The default value for the setting."
                            },
                            "min": {
                                "type": "number",
                                "description": "If applicable (number), the minimum value for the setting. Having both min and max will create a slider."
                            },
                            "max": {
                                "type": "number",
                                "description": "If applicable (number), the maximum value for the setting. Having both min and max will create a slider."
                            },
                            "step": {
                                "type": "number",
                                "description": "If applicable (number), the step value for the setting."
                            },
                            "suffix": {
                                "type": "string",
                                "description": "If applicable (number), the suffix for the setting. (for example set to % for a percentage)"
                            }
                        }
                    }
                }
            }
        }
    }
}

=== 3166790565/Euro-Truck-Simulator-2-Lane-Assist/ETS2LA/plugins/Test3/plugin.json
{
    "name": "Test3",
    "authors": [{
        "name": "Tumppi066",
        "url": "https://github.com/Tumppi066",
        "avatar": "https://avatars.githubusercontent.com/u/83072683?v=4"
    }],
    "description": "Lorem ea enim tempor Lorem in ad duis nisi. Est velit cillum occaecat eiusmod eiusmod aliquip.",
    "version": "1.0",
    "modules": [],
    "settings": [
        {
            "specials": [
                {
                    "special": "Title",
                    "special_data": "NOTHING HERE IS REAL"
                },
                {
                    "special": "Description",
                    "special_data": "This is a test plugin that I used!"
                },
                {
                    "special": "Separator"
                }
            ]
        },
        {
            "name": "Username",
            "key": "username",
            "description": "This is your public display name. It can be your real name or a pseudonym. You can only change this once every 30 days.",
            "type": {
                "type": "string"
            }
        },
        {
            "name": "Email",
            "key": "email",
            "description": "You can manage verified email addresses in your email settings",
            "type": {
                "type": "enum",
                "options": ["m@example.com", "m@google.com", "m@support.com"]
            }
        },
        {
            "name": "Test Boolean",
            "key": "test_boolean",
            "description": "Anim ullamco cillum proident aliqua elit. Nisi quis labore aute adipisicing elit do duis anim enim ullamco amet nisi minim. Consequat proident ad elit minim do exercitation id do amet velit mollit aute.",
            "type": {
                "type": "boolean"
            }
        },
        {
            "name": "Test array",
            "key": "test_array",
            "description": "Anim ullamco cillum proident aliqua elit. Nisi quis labore aute adipisicing elit do duis anim enim ullamco amet nisi minim. Consequat proident ad elit minim do exercitation id do amet velit mollit aute.",
            "type": {
                "type": "array",
                "value_type": "number"
            }
        },
        {
            "name": "Test Object",
            "key": "test_object",
            "description": "Anim ullamco cillum proident aliqua elit. Nisi quis labore aute adipisicing elit do duis anim enim ullamco amet nisi minim. Consequat proident ad elit minim do exercitation id do amet velit mollit aute.",
            "type": {
                "type": "object"
            }
        }
    ]
}
